#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MIS_DB")]
	public partial class MIS_DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMusteris(Musteris instance);
    partial void UpdateMusteris(Musteris instance);
    partial void DeleteMusteris(Musteris instance);
    partial void InsertMusteriBorcs(MusteriBorcs instance);
    partial void UpdateMusteriBorcs(MusteriBorcs instance);
    partial void DeleteMusteriBorcs(MusteriBorcs instance);
    #endregion
		
		public MIS_DBDataContext() : 
				base(global::MIS.Properties.Settings.Default.MIS_DBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MIS_DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MIS_DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MIS_DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MIS_DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Musteris> Musteris
		{
			get
			{
				return this.GetTable<Musteris>();
			}
		}
		
		public System.Data.Linq.Table<MusteriBorcs> MusteriBorcs
		{
			get
			{
				return this.GetTable<MusteriBorcs>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MusterisVeMusteriBorcs")]
		public ISingleResult<MusterisVeMusteriBorcsResult> MusterisVeMusteriBorcs()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MusterisVeMusteriBorcsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteris")]
	public partial class Musteris : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _musteriID;
		
		private string _musteriAlisverisTarihi;
		
		private int _musteriFisNo;
		
		private string _musteriAdSoyad;
		
		private int _musteriTel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmusteriIDChanging(int value);
    partial void OnmusteriIDChanged();
    partial void OnmusteriAlisverisTarihiChanging(string value);
    partial void OnmusteriAlisverisTarihiChanged();
    partial void OnmusteriFisNoChanging(int value);
    partial void OnmusteriFisNoChanged();
    partial void OnmusteriAdSoyadChanging(string value);
    partial void OnmusteriAdSoyadChanged();
    partial void OnmusteriTelChanging(int value);
    partial void OnmusteriTelChanged();
    #endregion
		
		public Musteris()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int musteriID
		{
			get
			{
				return this._musteriID;
			}
			set
			{
				if ((this._musteriID != value))
				{
					this.OnmusteriIDChanging(value);
					this.SendPropertyChanging();
					this._musteriID = value;
					this.SendPropertyChanged("musteriID");
					this.OnmusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriAlisverisTarihi", DbType="NVarChar(MAX)")]
		public string musteriAlisverisTarihi
		{
			get
			{
				return this._musteriAlisverisTarihi;
			}
			set
			{
				if ((this._musteriAlisverisTarihi != value))
				{
					this.OnmusteriAlisverisTarihiChanging(value);
					this.SendPropertyChanging();
					this._musteriAlisverisTarihi = value;
					this.SendPropertyChanged("musteriAlisverisTarihi");
					this.OnmusteriAlisverisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriFisNo", DbType="Int NOT NULL")]
		public int musteriFisNo
		{
			get
			{
				return this._musteriFisNo;
			}
			set
			{
				if ((this._musteriFisNo != value))
				{
					this.OnmusteriFisNoChanging(value);
					this.SendPropertyChanging();
					this._musteriFisNo = value;
					this.SendPropertyChanged("musteriFisNo");
					this.OnmusteriFisNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriAdSoyad", DbType="NVarChar(MAX)")]
		public string musteriAdSoyad
		{
			get
			{
				return this._musteriAdSoyad;
			}
			set
			{
				if ((this._musteriAdSoyad != value))
				{
					this.OnmusteriAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._musteriAdSoyad = value;
					this.SendPropertyChanged("musteriAdSoyad");
					this.OnmusteriAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriTel", DbType="Int NOT NULL")]
		public int musteriTel
		{
			get
			{
				return this._musteriTel;
			}
			set
			{
				if ((this._musteriTel != value))
				{
					this.OnmusteriTelChanging(value);
					this.SendPropertyChanging();
					this._musteriTel = value;
					this.SendPropertyChanged("musteriTel");
					this.OnmusteriTelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MusteriBorcs")]
	public partial class MusteriBorcs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _musteriBorcMusteriID;
		
		private int _musteriBorcFisNo;
		
		private int _musteriBorcCalisanID;
		
		private int _odenenMiktar;
		
		private int _musteriGuncelBorc;
		
		private bool _musteriBorcDurum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmusteriBorcMusteriIDChanging(int value);
    partial void OnmusteriBorcMusteriIDChanged();
    partial void OnmusteriBorcFisNoChanging(int value);
    partial void OnmusteriBorcFisNoChanged();
    partial void OnmusteriBorcCalisanIDChanging(int value);
    partial void OnmusteriBorcCalisanIDChanged();
    partial void OnodenenMiktarChanging(int value);
    partial void OnodenenMiktarChanged();
    partial void OnmusteriGuncelBorcChanging(int value);
    partial void OnmusteriGuncelBorcChanged();
    partial void OnmusteriBorcDurumChanging(bool value);
    partial void OnmusteriBorcDurumChanged();
    #endregion
		
		public MusteriBorcs()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriBorcMusteriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int musteriBorcMusteriID
		{
			get
			{
				return this._musteriBorcMusteriID;
			}
			set
			{
				if ((this._musteriBorcMusteriID != value))
				{
					this.OnmusteriBorcMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._musteriBorcMusteriID = value;
					this.SendPropertyChanged("musteriBorcMusteriID");
					this.OnmusteriBorcMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriBorcFisNo", DbType="Int NOT NULL")]
		public int musteriBorcFisNo
		{
			get
			{
				return this._musteriBorcFisNo;
			}
			set
			{
				if ((this._musteriBorcFisNo != value))
				{
					this.OnmusteriBorcFisNoChanging(value);
					this.SendPropertyChanging();
					this._musteriBorcFisNo = value;
					this.SendPropertyChanged("musteriBorcFisNo");
					this.OnmusteriBorcFisNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriBorcCalisanID", DbType="Int NOT NULL")]
		public int musteriBorcCalisanID
		{
			get
			{
				return this._musteriBorcCalisanID;
			}
			set
			{
				if ((this._musteriBorcCalisanID != value))
				{
					this.OnmusteriBorcCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._musteriBorcCalisanID = value;
					this.SendPropertyChanged("musteriBorcCalisanID");
					this.OnmusteriBorcCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odenenMiktar", DbType="Int NOT NULL")]
		public int odenenMiktar
		{
			get
			{
				return this._odenenMiktar;
			}
			set
			{
				if ((this._odenenMiktar != value))
				{
					this.OnodenenMiktarChanging(value);
					this.SendPropertyChanging();
					this._odenenMiktar = value;
					this.SendPropertyChanged("odenenMiktar");
					this.OnodenenMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriGuncelBorc", DbType="Int NOT NULL")]
		public int musteriGuncelBorc
		{
			get
			{
				return this._musteriGuncelBorc;
			}
			set
			{
				if ((this._musteriGuncelBorc != value))
				{
					this.OnmusteriGuncelBorcChanging(value);
					this.SendPropertyChanging();
					this._musteriGuncelBorc = value;
					this.SendPropertyChanged("musteriGuncelBorc");
					this.OnmusteriGuncelBorcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriBorcDurum", DbType="Bit NOT NULL")]
		public bool musteriBorcDurum
		{
			get
			{
				return this._musteriBorcDurum;
			}
			set
			{
				if ((this._musteriBorcDurum != value))
				{
					this.OnmusteriBorcDurumChanging(value);
					this.SendPropertyChanging();
					this._musteriBorcDurum = value;
					this.SendPropertyChanged("musteriBorcDurum");
					this.OnmusteriBorcDurumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class MusterisVeMusteriBorcsResult
	{
		
		private string _musteriAdSoyad;
		
		private string _musteriAlisverisTarihi;
		
		private int _musteriGuncelBorc;
		
		private int _odenenMiktar;
		
		private bool _musteriBorcDurum;
		
		public MusterisVeMusteriBorcsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriAdSoyad", DbType="NVarChar(MAX)")]
		public string musteriAdSoyad
		{
			get
			{
				return this._musteriAdSoyad;
			}
			set
			{
				if ((this._musteriAdSoyad != value))
				{
					this._musteriAdSoyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriAlisverisTarihi", DbType="NVarChar(MAX)")]
		public string musteriAlisverisTarihi
		{
			get
			{
				return this._musteriAlisverisTarihi;
			}
			set
			{
				if ((this._musteriAlisverisTarihi != value))
				{
					this._musteriAlisverisTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriGuncelBorc", DbType="Int NOT NULL")]
		public int musteriGuncelBorc
		{
			get
			{
				return this._musteriGuncelBorc;
			}
			set
			{
				if ((this._musteriGuncelBorc != value))
				{
					this._musteriGuncelBorc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odenenMiktar", DbType="Int NOT NULL")]
		public int odenenMiktar
		{
			get
			{
				return this._odenenMiktar;
			}
			set
			{
				if ((this._odenenMiktar != value))
				{
					this._odenenMiktar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriBorcDurum", DbType="Bit NOT NULL")]
		public bool musteriBorcDurum
		{
			get
			{
				return this._musteriBorcDurum;
			}
			set
			{
				if ((this._musteriBorcDurum != value))
				{
					this._musteriBorcDurum = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
